### PR TITLE
Repository Cleanup

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
( Draft | Need some questions answered )

Please check the **[Preview]**.

<br>

### Question

Where is `SVM.c_opt` located?

<br>

### Changes
- Formatted README
- Added license badge
- Added requirements
- Moved source code to Source
- Moved data to Data
- Moved test tool into Tools
- Adjusted paths

<br>

### Repository Suggestions

- Add tags

- Disable unused widgets:

  - `Packages`

  - `Releases`

- Disable unused tabs:

  - `Projects`

  - `Actions`

  - `Wiki`

[Preview]: https://github.com/ElectronicsArchiver/ADHD_Classifier

### CODE REVIEW

**Comment by HARDIntegral** [comment]
c_opt is a shared library that has to be built using the makefile

**Comment by ElectronicsArchiver** [comment]
Is `data.old.txt` in any form relevant to keep?

**Comment by ElectronicsArchiver** [comment]
Btw, isn't the gsl lib available (on newer ubuntu) as `libgsl-dev` not `ibgsl0ldbl`?

**Comment by ElectronicsArchiver** [comment]
Can't test my python refactorings without the database,..
Syntax is correct but~

**Comment by ElectronicsArchiver** [comment]
Moved makefile into library folder, adjusted paths, added `Tools/Build.sh` (supports `build` / `clean` arguments)

**Comment by HARDIntegral** [comment]
> Can't test my python refactorings without the database,..
> 
> Syntax is correct but~

I cannot make that data public, I'm sorry. Like the original read me said, these are tests for my research project

**Comment by HARDIntegral** [comment]
> Is `data.old.txt` in any form relevant to keep?

Nope

**Comment by ElectronicsArchiver** [comment]
> I cannot make that data public, I'm sorry. Like the original read me said, these are tests for my research project

Mhm well you can share an example (with fake data) though?
I could write a script to generate fake test data with the same format~

**Comment by HARDIntegral** [comment]
> > I cannot make that data public, I'm sorry. Like the original read me said, these are tests for my research project
> 
> 
> 
> Mhm well you can share an example (with fake data) though?
> 
> I could write a script to generate fake test data with the same format~

I added a sample.mat file that contains sample data

**Comment by ElectronicsArchiver** [comment]
Thank you, I will look into that after this PR, if that is fine with you?

**Comment by HARDIntegral** [comment]
> Thank you, I will look into that after this PR, if that is fine with you?

sure

**Comment by ElectronicsArchiver** [comment]
Ahh, your merge changes kinda screwed with the file system..
I can correct it and open a PR for it..
- 2 include / source folders
- build script was undone
- 2 locations.json
- ...

**Comment by HARDIntegral** [comment]
> Ahh, your merge changes kinda screwed with the file system.. I can correct it and open a PR for it..
> 
> * 2 include / source folders
> * build script was undone
> * 2 locations.json
> * ...

i think I fixed it, idk

**Comment by ElectronicsArchiver** [comment]
Well now you just copied the change from my commits..
*not something you should do*

Btw, the usage addition you made isn't correct though,
it would be:

```sh
Tools/Build.sh
```
and
```sh
Tools/Build.sh clean
```

**Comment by ElectronicsArchiver** [comment]
Sorry cut that last part, the Clean.sh didn't show up for some reason..
still, didn't require it~

**Comment by HARDIntegral** [comment]
that should be all of it right?

**Comment by HARDIntegral** [comment]
> Well now you just copied the change from my commits.. _not something you should do_
> 
> Btw, the usage addition you made isn't correct though, it would be:
> 
> ```shell
> Tools/Build.sh
> ```
> 
> and
> 
> ```shell
> Tools/Build.sh clean
> ```

eh was too lazy to figure out how to do it another way and I have work on the paper that this corresponds to

**Comment by ElectronicsArchiver** [comment]
Sorry, no, let me open a PR for them
so you don't copy my changes again..

**Pull request merged**
